### PR TITLE
Make SignalFlowClient implement AutoCloseable

### PR DESCRIPTION
**Pull request by einarpehrson**
To enable the use of try-with-resources.

### CODE REVIEW

**Review by breedx-splk — CHANGES_REQUESTED** [review]
If your intent is to use try-with-resources, I think this should be using `AutoCloseable` right? Also please add the `@Override` annotation and add a test that demonstrates try-with-resources.

**Comment by einarpehrson** [comment]
> If your intent is to use try-with-resources, I think this should be using `AutoCloseable` right?
@breedx-splk yes, you are right. Fixed.

> Also please add the `@Override` annotation and add a test that demonstrates try-with-resources.
@breedx-splk Done.

**Review by breedx-splk — APPROVED** [review]

**Comment by einarpehrson** [comment]
@breedx-splk would you mind merging this pull request? :)

**Comment by mateuszrzeszutek** [comment]
Merged. Thanks @einarpehrson for your contribution!

**Pull request merged**
